apiVersion: portal.apiconnect.ibm.com/v1beta1
kind: PortalCluster
metadata:
  name: portal
spec:
  version: 10.0.8.0
  profile: n1xc2.m8
  imagePullSecrets:
    - apic-registry-secret
  imageRegistry: image-registry.cluster-poc-7be4149f30480846757a2468f333dd09-0000.eu-de.containers.appdomain.cloud
  # imageRegistry: cp.icr.io/cp/apic
  mgmtPlatformEndpointCASecret:
    secretName: ingress-ca # Usually ingress-ca
  mgmtConsumerEndpointCASecret:
    secretName: ingress-ca # Usually ingress-ca
  #mgmtPlatformEndpointSvcCASecret:
  #  secretName:  # Usually management-ca
  #mgmtConsumerEndpointSvcCASecret:
  #  secretName:  # Usually management-ca
  portalAdminEndpoint:
    #ingressClassName: $INGRESS_CLASS
    annotations:
      cert-manager.io/issuer: ingress-issuer
    hosts:
    - name: api.portal.cluster-poc-7be4149f30480846757a2468f333dd09-0000.eu-de.containers.appdomain.cloud
      secretName: portal-admin
  portalUIEndpoint:
    #ingressClassName: $INGRESS_CLASS
    annotations:
      cert-manager.io/issuer: ingress-issuer
    hosts:
    - name: portal.cluster-poc-7be4149f30480846757a2468f333dd09-0000.eu-de.containers.appdomain.cloud
      secretName: portal-web
  databaseVolumeClaimTemplate:
    storageClassName: ibmc-vpc-block-10iops-tier
    volumeSize: 15Gi
  databaseLogsVolumeClaimTemplate:
    storageClassName: ibmc-vpc-block-10iops-tier
    volumeSize: 6Gi
  webVolumeClaimTemplate:
    storageClassName: ibmc-vpc-block-10iops-tier
    volumeSize: 8Gi
  backupVolumeClaimTemplate:
    storageClassName: ibmc-vpc-block-10iops-tier
    volumeSize: 15Gi
  adminVolumeClaimTemplate:
    storageClassName: ibmc-vpc-block-10iops-tier
    volumeSize: 6Gi
  certVolumeClaimTemplate:
    storageClassName: ibmc-vpc-block-10iops-tier
    volumeSize: 4Gi
  license:
    accept: true
    use: nonproduction
    license: L-DZZQ-MGVN8V
